### ISSUE TITLE
error windows

### ISSUE THREAD

**Issue by learnercrypto** [TheZ3ro/bitcoin-privatekey-db#17]
Traceback (most recent call last):
  File "C:\Users\Barthwal\Downloads\New folder (25)\bitcoin-privatekey-db-master\server.py", line 1, in <module>
    from flask import Flask, render_template
  File "C:\Users\Barthwal\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (C:\Users\Barthwal\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\__init__.py)

**Comment by TheZ3ro** [comment]
try with `pip install Jinja2==2.11.2`.

Your installed Jinja2 version is too new

**Comment by learnercrypto** [comment]
ERROR: Could not find a version that satisfies the requirement Jinja==2.11.2 (from versions: 0.8, 0.9, 1.0, 1.1, 1.2)
ERROR: No matching distribution found for Jinja==2.11.2
